# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_reportbuilder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportBuilder',
        ),
    ]
