# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 11:46
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20160506_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
